name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. 1.2.3)"
        required: true
        default: "0.0.1"

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: repo
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/packages
          path: packages
          token: ${{ env.GITHUB_TOKEN }}
      - name: Determine release tag
        id: vars
        run: |
          TAG="${{ github.event.release.tag_name || inputs.tag }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Create release-${{ steps.vars.outputs.tag }} branch
        run: |
          cd packages
          git checkout -b release-${{ steps.vars.outputs.tag }}
      - name: copy files into packages repo
        run: |
          mkdir -p packages/packages/preview/perlit/${{ steps.vars.outputs.tag }}
          cp -a repo/* packages/packages/preview/perlit/${{ steps.vars.outputs.tag }}*
      - name: update typst.toml
        run: sed -i "s/^version = \".*\"/version = \"${{ steps.vars.outputs.tag }}\"/" packages/packages/preview/perlit/${{ steps.vars.outputs.tag }}/typst.toml
      - name: update README.md
        run: sed -i "s/@preview\/perlit:[0-9]\+\.[0-9]\+\.[0-9]\+/@preview\/perlit:${{ steps.vars.outputs.tag }}/g" packages/packages/preview/perlit/${{ steps.vars.outputs.tag }}/README.md
      - name: Create PR
        run: |
          cd packages
          git add .
          git commit -m "release-${{ steps.vars.outputs.tag }}"
          git push https://${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/packages
          gh pr create --title "Automated PR: ${{ steps.vars.outputs.tag }}" --body "PR Generated by Github Actions" --head "new-push"
