name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. 1.2.3)"
        required: true
        default: "0.0.1"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repo
      - name: Determine release tag
        id: vars
        run: |
          TAG="${{ github.event.release.tag_name || inputs.tag }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: checkout package repo
        run: |
          git clone --depth 1 --no-checkout --filter="tree:0" https://github.com/${{ github.repository_owner }}/packages.git
          cd packages
          git sparse-checkout init
          git sparse-checkout set packages/preview/perlit
          git remote add upstream git@github.com:typst/packages
          git config remote.upstream.partialclonefilter tree:0
          git checkout main
      - name: copy files into packages repo
        run: |
          mkdir -p packages/packages/preview/perlit/${{ steps.vars.outputs.tag }}
          cp -a repo/* packages/packages/preview/perlit/${{ steps.vars.outputs.tag }}*
      - name: update typst.toml
        run: sed -i "s/^version = \".*\"/version = \"${{ steps.vars.outputs.tag }}\"/" packages/packages/preview/perlit/${{ steps.vars.outputs.tag }}/typst.toml
      - name: update README.md
        run: sed -i "s/@preview\/perlit:[0-9]\+\.[0-9]\+\.[0-9]\+/@preview\/perlit:${{ steps.vars.outputs.tag }}/g" packages/packages/preview/perlit/${{ steps.vars.outputs.tag }}/README.md
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        working-directory: packages
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update perlit preview to ${{ steps.vars.outputs.tag }}"
          branch: "perlit-preview-${{ steps.vars.outputs.tag }}"
          base: main
          title: "Update perlit preview to ${{ steps.vars.outputs.tag }}"
          body: |
            This PR updates the `perlit` preview to version `${{ steps.vars.outputs.tag }}`.
            Files copied from the main repository.
          path: "packages/packages/preview/perlit/${{ steps.vars.outputs.tag }}"
